from __future__ import annotations

_AE2_ITEM_MULTI_MATERIAL_METADATA: dict[str, int] = {
    "InvalidType": 0,
    "CertusQuartzCrystal": 0,
    "CertusQuartzCrystalCharged": 1,
    "CertusQuartzDust": 2,
    "NetherQuartzDust": 3,
    "Flour": 4,
    "Silicon": 5,
    "MatterBall": 6,
    "FluixCrystal": 7,
    "FluixDust": 8,
    "FluixPearl": 9,
    "PurifiedCertusQuartzCrystal": 10,
    "PurifiedNetherQuartzCrystal": 11,
    "PurifiedFluixCrystal": 12,
    "CalcProcessorPress": 13,
    "EngProcessorPress": 14,
    "LogicProcessorPress": 15,
    "SiliconPress": 16,
    "CalcProcessorPrint": 17,
    "EngProcessorPrint": 18,
    "LogicProcessorPrint": 19,
    "SiliconPrint": 20,
    "NamePress": 21,
    "LogicProcessor": 22,
    "CalcProcessor": 23,
    "EngProcessor": 24,
    "BasicCard": 25,
    "CardRedstone": 26,
    "CardCapacity": 27,
    "CardFuzzy": 28,
    "CardSpeed": 29,
    "CardInverter": 30,
    "CardCrafting": 31,
    "Cell1kPart": 32,
    "Cell4kPart": 33,
    "Cell16kPart": 34,
    "Cell64kPart": 35,
    "Cell2SpatialPart": 36,
    "Cell16SpatialPart": 37,
    "Cell128SpatialPart": 38,
    "EmptyStorageCell": 39,
    "WoodenGear": 40,
    "SkyDust": 41,
    "EnderDust": 42,
    "AnnihilationCore": 43,
    "FormationCore": 44,
    "Singularity": 45,
    "QESingularity": 46,
    "Wireless": 47,
    "WirelessBooster": 48,
    "IronDust": 49,
    "IronNugget": 50,
    "GoldDust": 51,
    "BlankPattern": 52,
    "AdvCard": 53,
    "LogicProcessorAsm": 54,
}


def ae2_item_material_metadata(material_name: str) -> int | None:
    return _AE2_ITEM_MULTI_MATERIAL_METADATA.get(material_name)
