services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      MINECRAFT_VERSIONS_DIR: /app/MinecraftVersions
      CORS_ORIGINS: http://localhost:5173,http://localhost
    volumes:
      - ./MinecraftVersions:/app/MinecraftVersions:ro
      - ./backend/logs:/app/backend/logs
      - ./backend/data/mods:/app/backend/data/mods
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./MinecraftVersions/26.2/item-textures:/usr/share/nginx/minecraft/item-textures:ro
      - ./MinecraftVersions/26.2/block-textures:/usr/share/nginx/minecraft/block-textures:ro
    depends_on:
      - backend
    restart: unless-stopped
